<meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=App::config('nazivApp')?></title>
    <link rel="stylesheet" href="<?=App::config('url')?>public/css/foundation.css">
    <link rel="stylesheet" href="<?=App::config('url')?>public/css/app.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  

    <?php 
if(isset($css)){
    echo "\t" . $css . "\n";
}
?>