<form class="log-in-form" 
    action="<?=App::config('url')?>Dom_Zdravlja/novo"
    method="POST">
  <h4 class="text-center">Dodavanje novog Doma Zdravlja</h4>
  <label>Naziv
    <input type="text" name="naziv" value="<?=$dom_zdravlja->$naziv?>">
  </label>

  <label>Doktor
    <input type="text" name="doktor" value="<?=$dom_zdravlja->$doktor?>">
  </label>

  <label>Bolnica
    <input type="text" name="bolnica" value="<?=$dom_zdravlja->$bolnica?>">
  </label>

  <label>Ordinacija
    <input type="text" name="ordinacija" value="<?=$dom_zdravlja->$ordinacija?>">
  </label>
  
  <?=$poruka?>

<div class="grid-x grid-padding-x">
  <div class="cell medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>dom_zdravlja/index">Nazad</a>
  </div>
  <div class="cell medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>

</form>