

<table>
    <thead>
         <tr>
         <th>
           </th>
            <th>Naziv</th>
            <th>Mjesto</th>
            <th>Bolnica</th>
            <th style="text-align: right;">
            <a href="<?=App::config('url')?>domzdravlja/novo">Dodaj novog</a>
            </th>
         </tr>
    </thead>

  <tbody>
       <?php foreach($entiteti as $red): ?>
          <tr>
                <td><?=$red->naziv?></td>
                <td><?=$red->mjesto?></td>
                <td><?=$red->bolnica?></td>
                 <td>
                 <a href="<?=App::config('url')?>domzdravlja/promjena?sifra=<?=$red->sifra?>">
                        <i title="promjena" class="fas fa-2x fa-pencil-alt"></i>
                    <?php if($red->ukupnopacijenata==0): ?>
                        <a href="<?=App::config('url')?>domzdravlja/brisanje?sifra=<?=$red->sifra?>"
                        onclick="return confirm('Sigurno obrisati<?=Funkcije::escapeSingleQuote($red->naziv) ?>?');">
                        <i title="brisanje" style="color: red" class="fas fa-trash-alt"></i></a>
                        <?php endif;?>
                </td>
              </tr>
         
       <?php endforeach; ?>
   </tbody>
</table>


