

<table>
    <thead>
         <tr>
            <th>Naziv</th>
            <th>Doktor</th>
            <th>Bolnica</th>
            <th>Ordinacija</th>
            <th style= "text-align: right;"><a href=""></a>Dodaj novi Dom Zdravlja</th>
         </tr>
    </thead>

<tbody>
       <?php foreach($domovizdravlja as $red): ?>
          <tr>
              <tr>
                <td><?=$red->naziv?></td>
                <td><?=$red->doktor?></td>
                <td><?=$red->bolnica?></td>
                <td><?=$red->ordinacija?></td>
                <td><a href="<?=App::config('url')?>domzdravlja/promjena?sifra=<?=$red->sifra?>">
                        <i title="promjena" class="fas fa-2x fa-pencil-alt"></i>
                    </a> 
                       
                        <a href="<?=App::config('url')?>domzdravlja/brisanje?sifra=<?=$domozdravlja->sifra?>"
                        onclick="return confirm('Sigurno obrisati <?=$red->naziv?> <?=$red->ordinacija?>?');">
                        <i title="brisanje" style="color: red" class="fas fa-trash-alt"></i></a>
                   
              </tr>
          </tr> 
       <?php endforeach; ?>
</tbody>

</table>


