<form class="log-in-form" 
    action="<?=App::config('url')?>domzdravlja/novo"
    method="POST">
  <h4 class="text-center">Dodavanje novog Doma Zdravlja</h4>
  <div class="grid-x grid-padding-x">
     <div class="cell">
        <label>Naziv
     <input type="text" name="naziv" value="<?=$domzdravlja->$naziv?>">
    </label>
   </div>
  </div>


  <div class="grid-x grid-padding-x">
  <div class="cell large-4">
  <label>Doktor
    <input type="text" name="doktor" value="<?=$domzdravlja->$doktor?>">
  </label>
  </div>
  <div class="cell large-4">
  <label>Bolnica
    <input type="text" name="bolnica" value="<?=$domzdravlja->$bolnica?>">
  </label>
  </div>
  <div class="cell large-4">
  <label>Ordinacija
    <input type="text" name="ordinacija" value="<?=$domzdravlja->$ordinacija?>">
  </label>
  </div>
</div> 

<div class="grid-x grid-padding-x">
     <div class="cell">
        <div class="callout">
        <?=$poruka?>
        </div>
   </div>
  </div>
  
  

<div class="grid-x grid-padding-x">
  <div class="cell medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>domzdravlja/index">Nazad</a>
  </div>
  <div class="cell medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>

</form>