<form class="log-in-form" 
    action="<?=App::config('url')?>Domzdravlja/promjena"
    method="POST">
  <h4 class="text-center">Promjena postojeceg Doma Zdravlja</h4>
  <label>Naziv
    <input type="text" name="naziv" value="<?=$entitet->naziv?>">
  </label>

  <div class="grid-x grid-padding-x">
  <div class="cell large-4">
  <label>Doktor
    <input type="text" name="doktor" value="<?=$entitet->doktor?>">
  </label>
  </div>
  <div class="cell large-4">
  <label>Bolnica
    <input type="text" name="bolnica" value="<?=$entitet->bolnica?>">
  </label>
  </div>
  <div class="cell large-4">
  <label>Ordinacija
    <input type="text" name="ordinacija" value="<?=$entitet->ordinacija?>">
  </label>
  </div>
</div> 

  
  
  <div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>domzdravlja/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Promjena"></input>
  </div>
</div>
<input type="hidden" name="sifra" value="<?=$smjer->sifra?>">
</form>
