<form class="log-in-form" 
    action="<?=App::config('url')?>Domzdravlja/promjena"
    method="POST">
  <h4 class="text-center">Promjena postojeceg Doma Zdravlja</h4> 
  
  <label>Naziv
    <input type="text" name="naziv" value="<?=$entitet->naziv?>">
  </label>

  <div class="grid-x grid-padding-x">
  <div class="cell large-4">
  <label>Doktor
    <input type="text" name="mjesto" value="<?=$entitet->mjesto?>">
  </label>
  </div>
  <div class="cell large-4">
  <label>Bolnica
    <!-- <input type="text" name="bolnica" value="<?=$entitet->bolnica?>"> -->
    <select name="bolnica" >
    <option value="">-- Odaberi Bolnicu --</option>
    <?php
    foreach ($bolnice as $bolnica):
      ?>
      <option value="<?=$bolnica->sifra?>" <?=($bolnica->sifra==$entitet->bolnica) ? "selected": "" ?>>  <?=$bolnica->naziv ?></option>
      <?php endforeach; ?>
    </select>
  </label>
  </div>
 
</div> 

<div class="grid-x grid-padding-x">
    <div class="cell">
      <hr />
      <input type="text" id="uvjet"
            placeholder="Unesite dio imena Doma Zdravlja">
      <table>
        <thead>
          <tr>
            <th>Dom Zdravlja</th>
            <th>Akcija</th>
          </tr>
        </thead>
        <tbody id="pacijenti">
          <?php
            if(isset($entitet->pacijent)):
        
          ?>
       <?php foreach($entitet->pacijent as $red): ?>
            <tr>
                <td><?=$red->ime . ' ' . $red->prezime;?></td>
                <td>
                <a class="brisanje" href="#" 
                id="p_<?=$red->sifra?>">
                        <i title="brisanje" style="color: red" 
                        class="fas fa-trash-alt"></i>
                        </a>
                </td>
            </tr>

        <?php endforeach; ?> 
        <?php
            endif;
        ?>
        </tbody>
      </table>
      <hr />
    </div>
  </div>

  
  
  <div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>domzdravlja/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Promjena"></input>
  </div>
</div>
<input type="hidden" name="sifra" value="<?=$entitet->sifra?>">
</form>
