<form class="log-in-form" 
    action="<?=App::config('url')?>pacijent/novo"
    method="POST">
  <h4 class="text-center">Dodavanje novog Pacijenta</h4>
  
  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
        <label>Ime
          <input type="text" name="ime" value="<?=$entitet->ime?>">
        </label>
      </div>
    <div class="cell large-6">
      <label>Prezime
        <input type="text"  name="prezime" value="<?=$entitet->prezime?>">
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>OiB
        <input type="text" name="oib" value="<?=$entitet->oib?>">
      </label>
    </div>
<div class="cell large-6">
  <label>Dom Zdravlja
    <input type="text" name="domzdravlja" value="<?=$entitet->domzdravlja?>">
  </label>
  </div>
</div> 

<div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Lijek
        <input type="text" name="lijek" value="<?=$entitet->lijek?>">
      </label>
    </div>

<div class="grid-x grid-padding-x">
     <div class="cell">
        <div class="callout">
        <?=$poruka?>
        </div>
   </div>
  </div>
  
  

<div class="grid-x grid-padding-x">
  <div class="cell medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>entitet/index">Nazad</a>
  </div>
  <div class="cell medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>

</form>