<h1 style="font-size: 1em;">Bolnice</h1>
<a href="<?=App::config('url')?>bolnica/novo">>Dodaj novu bolnicu</a>

<ul>
<?php foreach($bolnice as $bolnica): ?>
      <li>
           <?=$bolnica->naziv?>
           <a href="<?=App::config('url')?>bolnica/promjena?sifra=<?=$bolnica->sifra?>">
            Promjeni
            </a>
            <?php if($bolnica->ukupnodomovazdravlja==0): ?>
            <a href="<?=App::config('url')?>smjer/brisanje?sifra=<?=$smjer->sifra?>"
            onclick="return confirm('Sigurno obrisati <?=$smjer->naziv?>?');">
            <i title="brisanje" style="color: red" class="fas fa-trash-alt"></i></a>
        <?php endif;?>
      </li>    
    <?php endforeach; ?>
</ul>