<form class="log-in-form" 
    action="<?=App::config('url')?>bolnica/novo"
    method="POST">
  <h4 class="text-center">Dodavanje nove bolnice</h4>
  <div class="grid-x grid-padding-x">
    <div class="cell">
     
      <label>Naziv
        <input type="text" name="naziv" value="<?=$bolnica->naziv?>">
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
  <div class="cell large-4">
  
  <label>Ravnatelj
    <input type="text"  name="ravnatelj" value="<?=$bolnica->ravnatelj?>">
  </label>
  </div>
  <div class="cell large-4">
  
  <label>Odjel
    <input type="text" name="odjel" value="<?=$bolnica->odjel?>">
  </label>
  </div>
  <div class="cell large-4">
  
  <label>Doktor
  <input type="text" name="doktor" value="<?=$bolnica->doktor?>">
  </label>
  
  </div>
</div>
 
<div class="grid-x grid-padding-x">
    <div class="cell">
     <div class="callout">
      <?=$poruka?>
     </div>
    </div>
  </div>
  

<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>bolnica/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>

</form>