<div class="grid-x grid-margin-x">
    <div class="large-11 medium-11 small-10 cell">
        <form action="<?=App::config('url')?>pacijent/index" method="get">
           <!--  <input type="text" name="uvjet" id="uvjet" value="<?=$uvjet ??  "" ?>"
            placeholder="Unesite dio imena lijeka"> -->
        </form>
      <!-- <?php 
         isset($uvjet) ? $uvjet : ""  //ternary operator
      ?> -->

    </div>
    <div class="large-1 medium-1 small-2 cell" style="padding-top:5px;">
        
        <a href="<?=App::config('url')?>lijek/novo">
        <i class="fas fa-2x fa-plus-circle"></i>
        </a>
    </div>
</div>




<div class="grid-x grid-margin-x">
    <?php foreach($entiteti as $red): ?>
        <div class="large-3 cell">
            <div class="callout" style="min-height: 200x; text-align: center;">

           
                <img src="../<?=$red->slika?>" alt="<?=$red->naziv?> <?=$red->proizvodac?>">
               
               <?=$red->naziv?> 
               <?=$red->proizvodac?>
               <br />

               <?php if($red->naziv!=null): ?>
                <br />
                Naziv: <?=$red->naziv?>
                <?php endif; ?>
                
                <?php if($red->proizvodac!=null): ?>
                <br />
                Proizvodac: <?=$red->proizvodac?>
                <?php endif; ?>

                <hr />
                <a href="<?=App::config('url')?>lijek/promjena?sifra=<?=$red->sifra?>">
                        <i title="promjena" class="fas fa-2x fa-pencil-alt"></i>
                    </a> 
                    <?php if($red->naziv==0): ?>
                        <a href="<?=App::config('url')?>lijek/brisanje?sifra=<?=$red->sifra?>"
                        onclick="return confirm('Sigurno obrisati <?=Funkcije::escapeSingleQuote($red->naziv . ' ' . $red->proizvodac) ?>?');">
                        <i title="brisanje" style="color: red" class="fas fa-trash-alt"></i></a>
                    <?php endif; ?>

            </div>
        </div>
          <?php endforeach; ?>
          <?php
          echo $paginacija;

          ?>
        </div>

      <!--   <script>
        $( function() {
    function log( message ) {
      $( "<div>" ).text( message ).prependTo( "#log" );
      $( "#log" ).scrollTop( 0 );
    }
 
    $( "#birds" ).autocomplete({
      source: "search.php",
      minLength: 2,
      select: function( event, ui ) {
        log( "Selected: " + ui.item.value + " aka " + ui.item.id );
      }
    });
  } );
  </script>
 -->

 
<!-- <div class="ui-widget">
  <label for="birds">Birds: </label>
  <input id="birds">
</div>
 
<div class="ui-widget" style="margin-top:2em; font-family:Arial">
  Result:
  <div id="log" style="height: 200px; width: 300px; overflow: auto;" class="ui-widget-content"></div>
</div>
        </script>
 -->
