<a href="<?=App::config('url')?>lijek/novo">Dodaj novi lijek</a>

<div class="grid-x grid-margin-x">
    <?php foreach($entiteti as $red): ?>
        <div class="large-3 cell">
            <div class="callout" style="min-height: 200x; text-align: center;">

                <img src="<?=$red->slika?>" alt="<?=$red->naziv?> <?=$red->proizvodac?>">
               
               <?=$red->naziv?> 
               <?=$red->proizvodac?>
               <br />

               <?php if($red->naziv!=null): ?>
                <br />
                Naziv: <?=$red->naziv?>
                <?php endif; ?>
                
                <?php if($red->proizvodac!=null): ?>
                <br />
                Proizvodac: <?=$red->proizvodac?>
                <?php endif; ?>

                <hr />
                <a href="<?=App::config('url')?>lijek/promjena?sifra=<?=$red->sifra?>">
                        <i title="promjena" class="fas fa-2x fa-pencil-alt"></i>
                    </a> 
                    <?php if($red->naziv==0): ?>
                        <a href="<?=App::config('url')?>lijek/brisanje?sifra=<?=$red->sifra?>"
                        onclick="return confirm('Sigurno obrisati <?=Funkcije::escapeSingleQuote($red->naziv . ' ' . $red->proizvodac) ?>?');">
                        <i title="brisanje" style="color: red" class="fas fa-trash-alt"></i></a>
                    <?php endif; ?>

            </div>
        </div>
          <?php endforeach; ?>
          <?php
          echo $paginacija;

          ?>
        </div>

        

