<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Bolest</th>
            <th>Proizvodac</th>
            <th style="text-align: right;">
            <a href="<?=App::config('url')?>lijek/novo">Dodaj novi</a>
            </th>
        </tr>
    </thead>
    <tbody>
   <?php foreach($entiteti as $red): ?>
            <tr>
                <td><?=$red->naziv?> <?=$red->naziv?></td>
                <td><?=$red->bolest?></td>
                <td><?=$red->proizvodac?></td>
                <td>
                    <a href="<?=App::config('url')?>lijek/promjena?sifra=<?=$red->sifra?>">
                        <i title="promjena" class="fas fa-2x fa-pencil-alt"></i>
                    </a>
                    <?php if($red->bolest==0): ?>    
                        <a href="<?=App::config('url')?>lijek/brisanje?sifra=<?=$red->sifra?>"
                        onclick="return confirm('Sigurno obrisati <?=Funkcije::escapeSingleQuote($red->naziv . ' ' . $red->proizvodac) ?>?');">
                        <i title="brisanje" style="color: red" class="fas fa-trash-alt"></i></a>
                    <?php endif;?>
                </td>
            </tr>

        <?php endforeach; ?>
    </tbody>
</table>