<form class="log-in-form" 
    action="<?=App::config('url')?>lijek/novo"
    method="POST">
  <h4 class="text-center">Dodavanje novog Lijeka</h4>



  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
        <label>Naziv
          <input type="text" name="naziv" value="<?=$entitet->naziv?>">
        </label>
      </div>
    <div class="cell large-6">
      <label>Bolest
        <input type="text"  name="bolest" value="<?=$entitet->bolest?>">
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="cell">
      <label>Proizvodac
        <input type="text" name="proizvodac" value="<?=$entitet->proizvodac?>">
      </label>
    </div>
  </div>

  
 
<div class="grid-x grid-padding-x">
    <div class="cell">
     <div class="callout">
      <?=$poruka?>
     </div>
    </div>
  </div>
  

<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>lijek/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>

</form>